### ISSUE TITLE
flyby-satnogs-fetcher is stack smashing

### ISSUE THREAD

**Issue by Ciemon** [la1k/flyby#96] opened 2020-05-09 07:12 UTC
Hi, I've just installed flyby on an Unbuntu 19:10 system and running flyby-satnogs-fetcher gives the following error:

$ flyby-satnogs-fetcher
*** stack smashing detected ***: <unknown> terminated

Please let me know if I can help with this.

**Comment by ryeng** [comment] 2020-05-12 08:14
Hi Ciemon,

I can reproduce your problem, but not with flyby-satnogs-fetcher:

**Comment by bjorgan** [comment] 2020-05-12 18:31
I was also able to reproduce this, after setting `-fstack-protector` in gcc (I assume this is default in Ubuntu 19.10 but not in Debian) and running `flyby-transponder-dbutil` on a database fetched from SatNOGS. 

The transponder database has a hard limit of 10 transponders per satellite, but turns out that this limit is not correctly handled. The SatNOGS database has two satellites with more than 10 transponders (ISS and Es'Hail 2). This triggers the stack smashing error when Flyby attempts to write out of bounds. Fix coming up.

**Comment by Ciemon** [comment] 2020-05-13 14:23
Thank you both. 

I was unable to get a Traceback to help with the de-bugging, due to lack of knowledge/ability here.

I'm keen to use flyby on a headless Raspberry-Pi for doppler correction on my twin FT-817 setup, other software doesn't seem to have the fidelity required.

**Comment by bjorgan** [comment] 2020-05-13 19:06
Should be fixed in 4d6947f44a6dd6b776a47ee01f0bde99fa6b44b5. Closing this for now. Thanks for the issue!

**Closed by bjorgan** 2020-05-13 19:06 UTC
